$("div").first().css("background-color","red")
$("div").last().css({"background-color":"black","color":"white"})
$("div").eq(1).css({"background-color":"green","color":"yellow"})
$("div").filter("#container2").css({"background-color":"pink","color":"green"})
// $("h1").not("#h").css("bs","2px solid black")
